deploy1: 
  ReplicaNumber: 1

  containers:
      containerPort: 8080
      image: 'quay.io/amdevops2/openshift-demo'
      tag: 'chart_v1'

  service:
      servicePort: 8080
  argocd:
    syncwave:
      deployment: 5
      configmap: 1

deploy2: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/amdevops2/openshift-demo'
    tag: 'chart_v1'

  service:
    servicePort: 8080
  
  argocd:
    syncwave:
      deployment: 10
      configmap: 1

test: Healty

github:
  user: ori-schif
  token: empty-pass
  url: <https://api.github.com/repos/ori-schif/openshift/issues>