ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/amdevops2/openshift-demo'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness:
    httpGet:
      port: 8080
      scheme: HTTP
      path: /health/readiness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10 
    successThreshold: 1 
    failureThreshold: 3
  liveness:
    httpGet:
      port: 8080
      scheme: HTTP
      path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount: 
    path: /tmp/html

argocd:
  syncwave:
    deployment: 5
    configmap: 1